services:
  backend:
    build: ./delivery-api
    container_name: delivery-backend
    ports:
      - "3000:3000"
    volumes: 
    # Foi criado um volume para o arquivo pedidos.json, permitindo
    # que ele seja atualizado sem precisar reconstruir a imagem do backend.
      - ./delivery-api/pedidos.json:/app/pedidos.json
    environment:
      - NODE_ENV=production
    networks:
      - appnet

  frontend:
    build: ./interface
    container_name: delivery-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
